fix: add test-only `LockFile::read_pid` for cross-platform testing
Fixes an issue encountered in the CI overhaul PR #253. Open lock file
with read+write access and add test-only `read_pid` function that reads
from the same file handle. This works on Windows where exclusive locks
prevent reading through another file handle:

```
thread 'storage::lockfile::tests::test_lock_file_contains_pid' (8952) panicked at dash-spv\src\storage\lockfile.rs:72:59:
Should read lock file: Os { code: 33, kind: Uncategorized, message: "The process cannot access the file because another process has locked a portion of the file." }
```