fix: Stop loading headers twice into `ChainState::headers`  (#258)
* Add test

Results on current `v0.41-dev`

---- test_load_headers_from_storage::genesis_1_block stdout ----

thread 'test_load_headers_from_storage::genesis_1_block' (8727544) panicked at dash-spv/tests/header_sync_test.rs:380:5:
assertion `left == right` failed: Loaded count mismatch
  left: 0
 right: 1

---- test_load_headers_from_storage::checkpoint_1_block stdout ----

thread 'test_load_headers_from_storage::checkpoint_1_block' (8727541) panicked at dash-spv/tests/header_sync_test.rs:381:5:
assertion `left == right` failed: Chain state count mismatch
  left: 1
 right: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_load_headers_from_storage::checkpoint_60000_blocks stdout ----

thread 'test_load_headers_from_storage::checkpoint_60000_blocks' (8727542) panicked at dash-spv/tests/header_sync_test.rs:381:5:
assertion `left == right` failed: Chain state count mismatch
  left: 60000
 right: 120000

---- test_load_headers_from_storage::genesis_60000_blocks stdout ----

thread 'test_load_headers_from_storage::genesis_60000_blocks' (8727545) panicked at dash-spv/tests/header_sync_test.rs:380:5:
assertion `left == right` failed: Loaded count mismatch
  left: 59999
 right: 60000

* Stop loading headers twice into `ChainState::headers`

We currently load the headers twice into the header vector in `HeaderSyncManager::load_headers_from_storage`:

- First1. within `storage.load_chain_state`
- And then within `load_headers_from_storage` itself further down

```
2025-12-04T16:05:36.717779Z  INFO 🚀 Starting sync from checkpoint at height 1900000 instead of genesis (requested start height: 2200000)
2025-12-04T16:05:36.727966Z  INFO ✅ Loaded 2 headers into HeaderSyncManager in 0.00s (1129 headers/sec)
....

2025-12-05T04:31:15.980982Z ERROR Sequential sync manager error handling message: Validation error: Block at height 2300000 does not match checkpoint
```

```
2025-12-04T16:09:37.959349Z  INFO 🚀 Starting sync from checkpoint at height 1900000 instead of genesis (requested start height: 2200000)
2025-12-04T16:09:37.966703Z  INFO ✅ Loaded 1 headers into HeaderSyncManager in 0.00s (862 headers/sec)
´´´